sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - feature/docs
    - master

php:
  - 5.3
  - 5.6

env:
  - WP_VERSION=latest WP_MULTISITE=0

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest WP_MULTISITE=1

script:
  - phpcs --standard=phpcs.ruleset.xml $(find . -name '*.php')
  - phpunit
