sudo: false

language: php

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master
    - /^release\/.*$/

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

matrix:

before_script:
  - bash bin/lib/install_phpunit.sh
  - bash bin/lib/install_wp_tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

script:
  - vendor/bin/phpunit --report-useless-tests --verbose
